#! /bin/sh -ex

#check that data directory exists
if [ ! -d /data ]; then
  echo usage: podman -v local_directory:/data:Z
  exit 1
fi

#check if image is already available or download it
if [ -f "$IMAGE" ]; then
  echo "Using $IMAGE."
else 
  if [ -z $ISO_URL ]; then
    echo "ISO ${IMAGE} wasn't found on local path, and no ISO_URL environment variable specified - aborting"
    exit 1
  else
    echo "Attempting to download ISO from ${ISO_URL}"
    curl -o $IMAGE $ISO_URL
  fi
fi

mkdir -p $IPXE_DIR

cat > $IPXE_DIR/ipxe << EOF
#!ipxe                                                                                                                                                                                    
set live_url ${BASE_URL}
kernel \${live_url}/vmlinuz ignition.config.url=\${live_url}/config.ign coreos.live.rootfs_url=\${live_url}/rootfs.img ${KERNEL_OPTS}
initrd \${live_url}/initrd.img
boot       
EOF

export PXE_IMAGES=`isoinfo -i $IMAGE -f |grep -i images/pxeboot`
for img in $PXE_IMAGES; do
  export name=`basename ${img,,} | sed 's/\;1//' | sed 's/\.$//'`
  isoinfo -i $IMAGE -x $img > $IPXE_DIR/$name
 done
 
echo '{' > $IPXE_DIR/config.ign
isoinfo -i $IMAGE -x '/IMAGES/IGNITION.IMG;1' | xz -dc - | sed '1d; $d' >> $IPXE_DIR/config.ign
echo '}' >> $IPXE_DIR/config.ign

#podman run  -v $IPXE_DIR:/app:ro -p 8080:8080 -d --rm bitnami/nginx:latest
